import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { Card } from "@/components/ui/card";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function NavBar() {
  return (
    <Card className="flex flex-row items-center justify-center gap-5 w-[75%] text-lg">
      <p className="font-bold">YTsnatch</p>
      <ThemeToggle />
    </Card>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col min-h-screen">
            <div className="flex flex-row w-full px-5 py-10 items-center justify-center">
              <div className="flex flex-col items-center justify-center w-full gap-10">
                <NavBar />
              </div>
            </div>
            <div className="p-0 flex-1">{children}</div>
            <div className="p-10 flex flex-row items-center justify-center w-full">
              <p className="text-center text-xs">
                Stratos Thivaios © 2026
                <br />
                MIT License
              </p>
            </div>
          </div>
          <Toaster richColors={true} position="top-center" closeButton={true} />
        </ThemeProvider>
      </body>
    </html>
  );
}
